/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as TodosIndexRouteImport } from './routes/todos.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as BoardsBoardIdRouteImport } from './routes/boards_.$boardId'
import { Route as BoardsNewRouteImport } from './routes/boards.new'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as ApiTodosIndexRouteImport } from './routes/api/todos/index'
import { Route as ApiItemsIndexRouteImport } from './routes/api/items/index'
import { Route as ApiColumnsIndexRouteImport } from './routes/api/columns/index'
import { Route as ApiBoardsIndexRouteImport } from './routes/api/boards/index'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as BoardsBoardIdSettingsRouteImport } from './routes/boards_.$boardId_.settings'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiTodosTodoIdRouteImport } from './routes/api/todos/$todoId'
import { Route as ApiItemsItemIdRouteImport } from './routes/api/items/$itemId'
import { Route as ApiColumnsColumnIdRouteImport } from './routes/api/columns/$columnId'
import { Route as ApiBoardsBoardIdRouteImport } from './routes/api/boards/$boardId'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as BoardsBoardIdColumnsColumnIdRouteImport } from './routes/boards_.$boardId_.columns_.$columnId'
import { Route as BoardsBoardIdCardsCardIdRouteImport } from './routes/boards_.$boardId_.cards_.$cardId'
import { Route as ApiItemsItemIdCommentsRouteImport } from './routes/api/items/$itemId.comments'
import { Route as BoardsBoardIdColumnsColumnIdSettingsRouteImport } from './routes/boards_.$boardId_.columns_.$columnId_.settings'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards_/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsNewRoute = BoardsNewRouteImport.update({
  id: '/boards/new',
  path: '/boards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const ApiTodosIndexRoute = ApiTodosIndexRouteImport.update({
  id: '/api/todos/',
  path: '/api/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsIndexRoute = ApiItemsIndexRouteImport.update({
  id: '/api/items/',
  path: '/api/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiColumnsIndexRoute = ApiColumnsIndexRouteImport.update({
  id: '/api/columns/',
  path: '/api/columns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsIndexRoute = ApiBoardsIndexRouteImport.update({
  id: '/api/boards/',
  path: '/api/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdSettingsRoute = BoardsBoardIdSettingsRouteImport.update({
  id: '/boards_/$boardId_/settings',
  path: '/boards/$boardId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiTodosTodoIdRoute = ApiTodosTodoIdRouteImport.update({
  id: '/api/todos/$todoId',
  path: '/api/todos/$todoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsItemIdRoute = ApiItemsItemIdRouteImport.update({
  id: '/api/items/$itemId',
  path: '/api/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiColumnsColumnIdRoute = ApiColumnsColumnIdRouteImport.update({
  id: '/api/columns/$columnId',
  path: '/api/columns/$columnId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsBoardIdRoute = ApiBoardsBoardIdRouteImport.update({
  id: '/api/boards/$boardId',
  path: '/api/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const BoardsBoardIdColumnsColumnIdRoute =
  BoardsBoardIdColumnsColumnIdRouteImport.update({
    id: '/boards_/$boardId_/columns_/$columnId',
    path: '/boards/$boardId/columns/$columnId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BoardsBoardIdCardsCardIdRoute =
  BoardsBoardIdCardsCardIdRouteImport.update({
    id: '/boards_/$boardId_/cards_/$cardId',
    path: '/boards/$boardId/cards/$cardId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiItemsItemIdCommentsRoute = ApiItemsItemIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiItemsItemIdRoute,
} as any)
const BoardsBoardIdColumnsColumnIdSettingsRoute =
  BoardsBoardIdColumnsColumnIdSettingsRouteImport.update({
    id: '/boards_/$boardId_/columns_/$columnId_/settings',
    path: '/boards/$boardId/columns/$columnId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/invitations': typeof InvitationsRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirect': typeof RedirectRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/boards/new': typeof BoardsNewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/boards': typeof BoardsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/todos': typeof TodosIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/boards/$boardId': typeof ApiBoardsBoardIdRoute
  '/api/columns/$columnId': typeof ApiColumnsColumnIdRoute
  '/api/items/$itemId': typeof ApiItemsItemIdRouteWithChildren
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/api/boards': typeof ApiBoardsIndexRoute
  '/api/columns': typeof ApiColumnsIndexRoute
  '/api/items': typeof ApiItemsIndexRoute
  '/api/todos': typeof ApiTodosIndexRoute
  '/api/items/$itemId/comments': typeof ApiItemsItemIdCommentsRoute
  '/boards/$boardId/cards/$cardId': typeof BoardsBoardIdCardsCardIdRoute
  '/boards/$boardId/columns/$columnId': typeof BoardsBoardIdColumnsColumnIdRoute
  '/boards/$boardId/columns/$columnId/settings': typeof BoardsBoardIdColumnsColumnIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/invitations': typeof InvitationsRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/redirect': typeof RedirectRoute
  '/signup': typeof SignupRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/boards/new': typeof BoardsNewRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/boards': typeof BoardsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/todos': typeof TodosIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/boards/$boardId': typeof ApiBoardsBoardIdRoute
  '/api/columns/$columnId': typeof ApiColumnsColumnIdRoute
  '/api/items/$itemId': typeof ApiItemsItemIdRouteWithChildren
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/boards/$boardId/settings': typeof BoardsBoardIdSettingsRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/api/boards': typeof ApiBoardsIndexRoute
  '/api/columns': typeof ApiColumnsIndexRoute
  '/api/items': typeof ApiItemsIndexRoute
  '/api/todos': typeof ApiTodosIndexRoute
  '/api/items/$itemId/comments': typeof ApiItemsItemIdCommentsRoute
  '/boards/$boardId/cards/$cardId': typeof BoardsBoardIdCardsCardIdRoute
  '/boards/$boardId/columns/$columnId': typeof BoardsBoardIdColumnsColumnIdRoute
  '/boards/$boardId/columns/$columnId/settings': typeof BoardsBoardIdColumnsColumnIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/invitations': typeof InvitationsRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/redirect': typeof RedirectRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/boards/new': typeof BoardsNewRoute
  '/boards_/$boardId': typeof BoardsBoardIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/todos/': typeof TodosIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/boards/$boardId': typeof ApiBoardsBoardIdRoute
  '/api/columns/$columnId': typeof ApiColumnsColumnIdRoute
  '/api/items/$itemId': typeof ApiItemsItemIdRouteWithChildren
  '/api/todos/$todoId': typeof ApiTodosTodoIdRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/boards_/$boardId_/settings': typeof BoardsBoardIdSettingsRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/api/boards/': typeof ApiBoardsIndexRoute
  '/api/columns/': typeof ApiColumnsIndexRoute
  '/api/items/': typeof ApiItemsIndexRoute
  '/api/todos/': typeof ApiTodosIndexRoute
  '/api/items/$itemId/comments': typeof ApiItemsItemIdCommentsRoute
  '/boards_/$boardId_/cards_/$cardId': typeof BoardsBoardIdCardsCardIdRoute
  '/boards_/$boardId_/columns_/$columnId': typeof BoardsBoardIdColumnsColumnIdRoute
  '/boards_/$boardId_/columns_/$columnId_/settings': typeof BoardsBoardIdColumnsColumnIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/invitations'
    | '/invite'
    | '/login'
    | '/logout'
    | '/posts'
    | '/profile'
    | '/redirect'
    | '/signup'
    | '/users'
    | '/api/users'
    | '/boards/new'
    | '/boards/$boardId'
    | '/posts/$postId'
    | '/users/$userId'
    | '/boards'
    | '/posts/'
    | '/todos'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/boards/$boardId'
    | '/api/columns/$columnId'
    | '/api/items/$itemId'
    | '/api/todos/$todoId'
    | '/api/users/$userId'
    | '/boards/$boardId/settings'
    | '/posts/$postId/deep'
    | '/api/boards'
    | '/api/columns'
    | '/api/items'
    | '/api/todos'
    | '/api/items/$itemId/comments'
    | '/boards/$boardId/cards/$cardId'
    | '/boards/$boardId/columns/$columnId'
    | '/boards/$boardId/columns/$columnId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/invitations'
    | '/invite'
    | '/login'
    | '/logout'
    | '/profile'
    | '/redirect'
    | '/signup'
    | '/api/users'
    | '/boards/new'
    | '/boards/$boardId'
    | '/posts/$postId'
    | '/users/$userId'
    | '/boards'
    | '/posts'
    | '/todos'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/boards/$boardId'
    | '/api/columns/$columnId'
    | '/api/items/$itemId'
    | '/api/todos/$todoId'
    | '/api/users/$userId'
    | '/boards/$boardId/settings'
    | '/posts/$postId/deep'
    | '/api/boards'
    | '/api/columns'
    | '/api/items'
    | '/api/todos'
    | '/api/items/$itemId/comments'
    | '/boards/$boardId/cards/$cardId'
    | '/boards/$boardId/columns/$columnId'
    | '/boards/$boardId/columns/$columnId/settings'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/customScript.js'
    | '/deferred'
    | '/invitations'
    | '/invite'
    | '/login'
    | '/logout'
    | '/posts'
    | '/profile'
    | '/redirect'
    | '/signup'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/boards/new'
    | '/boards_/$boardId'
    | '/posts/$postId'
    | '/users/$userId'
    | '/boards/'
    | '/posts/'
    | '/todos/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/api/boards/$boardId'
    | '/api/columns/$columnId'
    | '/api/items/$itemId'
    | '/api/todos/$todoId'
    | '/api/users/$userId'
    | '/boards_/$boardId_/settings'
    | '/posts_/$postId/deep'
    | '/api/boards/'
    | '/api/columns/'
    | '/api/items/'
    | '/api/todos/'
    | '/api/items/$itemId/comments'
    | '/boards_/$boardId_/cards_/$cardId'
    | '/boards_/$boardId_/columns_/$columnId'
    | '/boards_/$boardId_/columns_/$columnId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  InvitationsRoute: typeof InvitationsRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PostsRoute: typeof PostsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RedirectRoute: typeof RedirectRoute
  SignupRoute: typeof SignupRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  BoardsNewRoute: typeof BoardsNewRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  TodosIndexRoute: typeof TodosIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiBoardsBoardIdRoute: typeof ApiBoardsBoardIdRoute
  ApiColumnsColumnIdRoute: typeof ApiColumnsColumnIdRoute
  ApiItemsItemIdRoute: typeof ApiItemsItemIdRouteWithChildren
  ApiTodosTodoIdRoute: typeof ApiTodosTodoIdRoute
  BoardsBoardIdSettingsRoute: typeof BoardsBoardIdSettingsRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
  ApiBoardsIndexRoute: typeof ApiBoardsIndexRoute
  ApiColumnsIndexRoute: typeof ApiColumnsIndexRoute
  ApiItemsIndexRoute: typeof ApiItemsIndexRoute
  ApiTodosIndexRoute: typeof ApiTodosIndexRoute
  BoardsBoardIdCardsCardIdRoute: typeof BoardsBoardIdCardsCardIdRoute
  BoardsBoardIdColumnsColumnIdRoute: typeof BoardsBoardIdColumnsColumnIdRoute
  BoardsBoardIdColumnsColumnIdSettingsRoute: typeof BoardsBoardIdColumnsColumnIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/boards_/$boardId': {
      id: '/boards_/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/new': {
      id: '/boards/new'
      path: '/boards/new'
      fullPath: '/boards/new'
      preLoaderRoute: typeof BoardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/api/todos/': {
      id: '/api/todos/'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/': {
      id: '/api/items/'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/columns/': {
      id: '/api/columns/'
      path: '/api/columns'
      fullPath: '/api/columns'
      preLoaderRoute: typeof ApiColumnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards/': {
      id: '/api/boards/'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards_/$boardId_/settings': {
      id: '/boards_/$boardId_/settings'
      path: '/boards/$boardId/settings'
      fullPath: '/boards/$boardId/settings'
      preLoaderRoute: typeof BoardsBoardIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/todos/$todoId': {
      id: '/api/todos/$todoId'
      path: '/api/todos/$todoId'
      fullPath: '/api/todos/$todoId'
      preLoaderRoute: typeof ApiTodosTodoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$itemId': {
      id: '/api/items/$itemId'
      path: '/api/items/$itemId'
      fullPath: '/api/items/$itemId'
      preLoaderRoute: typeof ApiItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/columns/$columnId': {
      id: '/api/columns/$columnId'
      path: '/api/columns/$columnId'
      fullPath: '/api/columns/$columnId'
      preLoaderRoute: typeof ApiColumnsColumnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards/$boardId': {
      id: '/api/boards/$boardId'
      path: '/api/boards/$boardId'
      fullPath: '/api/boards/$boardId'
      preLoaderRoute: typeof ApiBoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/boards_/$boardId_/columns_/$columnId': {
      id: '/boards_/$boardId_/columns_/$columnId'
      path: '/boards/$boardId/columns/$columnId'
      fullPath: '/boards/$boardId/columns/$columnId'
      preLoaderRoute: typeof BoardsBoardIdColumnsColumnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards_/$boardId_/cards_/$cardId': {
      id: '/boards_/$boardId_/cards_/$cardId'
      path: '/boards/$boardId/cards/$cardId'
      fullPath: '/boards/$boardId/cards/$cardId'
      preLoaderRoute: typeof BoardsBoardIdCardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$itemId/comments': {
      id: '/api/items/$itemId/comments'
      path: '/comments'
      fullPath: '/api/items/$itemId/comments'
      preLoaderRoute: typeof ApiItemsItemIdCommentsRouteImport
      parentRoute: typeof ApiItemsItemIdRoute
    }
    '/boards_/$boardId_/columns_/$columnId_/settings': {
      id: '/boards_/$boardId_/columns_/$columnId_/settings'
      path: '/boards/$boardId/columns/$columnId/settings'
      fullPath: '/boards/$boardId/columns/$columnId/settings'
      preLoaderRoute: typeof BoardsBoardIdColumnsColumnIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiItemsItemIdRouteChildren {
  ApiItemsItemIdCommentsRoute: typeof ApiItemsItemIdCommentsRoute
}

const ApiItemsItemIdRouteChildren: ApiItemsItemIdRouteChildren = {
  ApiItemsItemIdCommentsRoute: ApiItemsItemIdCommentsRoute,
}

const ApiItemsItemIdRouteWithChildren = ApiItemsItemIdRoute._addFileChildren(
  ApiItemsItemIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  InvitationsRoute: InvitationsRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PostsRoute: PostsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RedirectRoute: RedirectRoute,
  SignupRoute: SignupRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  BoardsNewRoute: BoardsNewRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  TodosIndexRoute: TodosIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiBoardsBoardIdRoute: ApiBoardsBoardIdRoute,
  ApiColumnsColumnIdRoute: ApiColumnsColumnIdRoute,
  ApiItemsItemIdRoute: ApiItemsItemIdRouteWithChildren,
  ApiTodosTodoIdRoute: ApiTodosTodoIdRoute,
  BoardsBoardIdSettingsRoute: BoardsBoardIdSettingsRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
  ApiBoardsIndexRoute: ApiBoardsIndexRoute,
  ApiColumnsIndexRoute: ApiColumnsIndexRoute,
  ApiItemsIndexRoute: ApiItemsIndexRoute,
  ApiTodosIndexRoute: ApiTodosIndexRoute,
  BoardsBoardIdCardsCardIdRoute: BoardsBoardIdCardsCardIdRoute,
  BoardsBoardIdColumnsColumnIdRoute: BoardsBoardIdColumnsColumnIdRoute,
  BoardsBoardIdColumnsColumnIdSettingsRoute:
    BoardsBoardIdColumnsColumnIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
